name: Docker CI Pipeline

# when should the pipeline run? (main)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # specify OS for github runner
    runs-on: ubuntu-latest

    steps:
      # download my code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # set up docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # builds the image automatically
      - name: Build Docker Image
        run: docker build -t ow-comps-api .